root_folder = fullfile('C:\','Users','Jade_Ericson','Documents','MATLAB','Training','test_set');
    categories = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'A', 'b', 'B', 'C', ...
    'd', 'D', 'e', 'E', 'f', 'F', 'g', 'G', 'h', 'H', 'I', 'J', 'K', 'L', ...
    'M', 'n', 'N', 'O', 'P', 'q', 'Q', 'r', 'R', 'S', 't', 'T', 'U', ...
    'V', 'W', 'X', 'Y', 'Z'};

test_set = imageDatastore(fullfile(root_folder,categories),'LabelSource','foldernames',...
	'ReadFcn',@gray2rgb24);
% test_set = imageDatastore(fullfile(root_folder,categories),'LabelSource','foldernames');

test_set_labels = test_set.Labels;
% View the number of samples per category
tbl = countEachLabel(test_set)
